microsoft/vscode-eslint

- eslint/README.md
Explain where to change the `configuration`, which actually is a `setting`.
> Use Settings instead of Configuration

- eslint/README.md
Started by fixing the "commond" typo. Then made some formatting improvements.
> readme: typo fix and formatting

- eslint/README.md
Fixed a typo in the readme resulting in a slightly broken link.
> Fixed typo

- .vscode/launch.json
> Update sourceMaps launch option to true

- .vscode/launch.json
Detail: https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented
> Update Variables Reference

- README.md
- client/src/extension.ts
- package.json
- server/src/eslintServer.ts
> Add a NODE_ENV configuration setting for eslint

- server/src/diff.ts
> Fix typo in diff.ts

- server/src/eslintServer.ts
> Fix typo in eslintServer.ts

- client/package-lock.json
- client/package.json
- client/src/extension.ts
- package.json
I cannot stand seeing this anymore:
> adopt backgroundColor option for status bar item

- .gitignore
I wonder if Microsoft developers need it, but I'm uploading it just in case.
> Add exception to a .gitignore

- README.md
For easier navigation of the document
> Added index to README.md

- client/src/client.ts
> Reload .eslintrc.cjs config without restart

- client/src/client.ts
- client/src/tasks.ts
Just doing a bit of housekeeping of passing the type information with `config.get` :)
> Use typed config.get

- README.md
Because the explanation in this section wasn't very clear to me, I added some examples of other pre-release and regular release version numbers
> Add more version number examples

- server/src/eslintServer.ts
Escape special characters in regular expressions for comments.
When figuring out if there is already an `eslint-disable` comment on the line before, the extension uses regular expressions to match comments. But comments include characters that appear naturally in regular expressions, like `*`. So the need to be replaced for construction of the regular expression. Otherwise adding the comment can fail when the previous line happens to include ` eslint-disable-next-line` even if not in a comment, or in languages that are not in the pre-defined list and thus use `/**` as a block comment indicator.
The regular expression to escape regular expressions is inspired by [ones commonly found e.g. on StackOverflow](https://stackoverflow.com/a/6969486/935676).
Fixes #1610 see there for more …
> Escape special characters in regular expressions for comments

- server/src/eslintServer.ts
> Fixes #1657: ESLint autofix doesn't work

- build/azure-pipelines/pre-release.yml
- build/azure-pipelines/release.yml
I have fixed an outstanding issue with Terrapin so I am wondering if we could re-enable it.
> Engineering - re-enable Terrapin

- README.md
> Fixes #1746: Why not integrate version 2.4.2 into the main branch?

- README.md
> Fixes #1750: Update Readme to reflect new vscode specs

- server/src/eslint.ts
> feat: support json, json5, jsonc in eslint.probe setting

- client/src/client.ts
> Fixes #1863: eslint.packageManager deprecated but error message says to use it

- README.md
- package.json
> Fixes  #1879: Document behavior and defaults of useFlatConfig across ESLint v8, v9, v10

- package.json
> Fixes #1885: JSON schema for useFlatConfig can be more specific

- client/src/node-utils.ts
> Fixes #1981: TypeError: Cannot read properties of undefined (reading 'isFile')

- $shared/settings.ts
- client/src/client.ts
- package.json
- server/src/eslint.ts
- server/src/eslintServer.ts
Continues the work from https://github.com/microsoft/vscode-eslint/pull/1945
> Add `eslint.codeActionsOnSave.options`

- client/src/client.ts
Adding the supported flat configuration file extensions as documented in https://eslint.org/docs/latest/use/configure/configuration-files.
> Add all possible flat configuration extensions
