eslint-server/src/server.ts
Thank you for the excellent extension!
To show ruleId is helpful to developers.
- If people want to know the rule's details, they can search with the
ruleId.
- If people want to disable the warning, they can write a
disable-comment with the ruleId.
So I'd like to show ruleId in tips.
=> Update: Show ruleId in tips

eslint-server/src/server.ts
Hides the `(ruleId)` part from the message if the ruleId is null.
=> fix(errors): hide ruleId if no ruleId applies. Closes #52

eslint-server/src/lib/eslint.ts, eslint-server/src/lib/protocol.ts, eslint-server/src/server.ts, eslint/extension.ts, eslint/lib/eslint-autofix-controller.ts, eslint/lib/eslint.ts, eslint/lib/protocol.ts, eslint/package.json
Refs #10 and #18.
Hello, thank you for the great extension!
The purpose of this PR is that adding the feature of ESLint's Autofix.
This PR is adding one command and one option.
- `eslint.executeAutofix` command executes Autofix on the current document.
- If `eslint.enableAutofixOnSave` option was enabled then it executes Autofix when you saved a document.
I'm happy if this PR is accepted.
And I'm happy to follow reviews and directions.
(I'm a beginner on TypeScript and VSCode extensions.)
Regards.
=> Add autofix supports.

eslint-server/src/server.ts
ESLint 3.1.0 starts to support the range of lint results (refs
https://github.com/eslint/eslint/pull/6640).
This PR adds the supports for the range feature into vscode-eslint extension.
=> Update: supports the range of lint results

eslint-server/src/server.ts
- `problem.line`, `problem.column`, `problem.endLine`, and
`problem.endColumn` may be zero.
- In that case, `vscode-eslint` seems to crash silently.
- This PR modifies the location calculation to avoid the crash.
=> Fixes zero location support

eslint/extension.ts
I would like to propose that we do not pass focus to the output channel when we open it automatically.
@dbaeumer fyi
=> preserve focus when showing output channel

client/src/extension.ts
Modify error message when eslint can't be found to improve the user experience.  Since npm is the default setting but most people are using yarn (see state of js data) including the vs code examples, add "If you are using yarn instead of npm set the setting `"eslint.packageManager": "yarn"`".  An even more improved user experience would be to check both.  see #374
=> update error message and add a hint to update yarn setting if using yarn

client/src/command.ts, client/src/extension.ts, client/src/tasks.ts, package.json
The extension currently has a command to `Create '.eslintrc.json' file`, but I would prefer to use `.eslintrc.yml`.
This PR adds functionality to generate a Yaml file with the same settings as the JSON.
closes #409
=> Use eslint --init to generate configuration

README.md, client/src/extension.ts, package.json, server/src/eslintServer.ts
Per the discussion in #345 it is useful toi be able to select the node version to run ESLint as. This adds the eslint.server.runtime setting which can be set to the path of the node binary to use.
=> Allow setting the node runtime to use for the language server. Fixes #345

server/src/eslintServer.ts
I spotted a typo in one of the error strings - this PR fixes that and also a few others in `eslintServer.ts`.
Thanks for the awesome extension! 😄
=> Fix some typos in eslintServer

client/src/extension.ts, server/src/eslintServer.ts
* Added Suppress rule for this line / Suppress rule for file quick actions (#245)
* Added show documentation quick action
* Fix possible issue with incorrect command run when 2 rule single fixes are available. This is due to `CommandIds.applySingleFix` getting overriden inside `commands` by the last added single fix quick action. The fix is to include the `ruleId` in the key when adding to `commands`.
=> Added Suppress rule for this line / Suppress rule for file quick actions / Show documentation

.travis.yml
Improve the pipeline using jobs instead of a single script to build all the pipeline commands.
Also I've splitted the `npm run compile` to run the `compile:client` and `compile:server` so it's easier to find if there is any compile problem.
See pipeline example -> https://travis-ci.org/angulito/vscode-eslint/builds/448863504
=> Improve pipeline

README.md, client/src/extension.ts, package.json, server/src/eslintServer.ts
* Fix issue with 'Fix all rule' quick action not appearing (mentioned in [comment of #530](https://github.com/Microsoft/vscode-eslint/pull/530#issuecomment-439315219))
* Add setting eslint.suppressCodeActionComment with options `sameLine` or `newLine` (#573)
* Add setting eslint.showSuppressCodeAction [comment of #530](https://github.com/Microsoft/vscode-eslint/pull/530#issuecomment-436269570)
* Add setting eslint.showDocumentationCodeAction [comment of #530](https://github.com/Microsoft/vscode-eslint/pull/530#issuecomment-436269570)
=> disable-eslint fixes and improvements

README.md
Documentation for `changeProcessCWD` is incorrect as outlined in https://github.com/Microsoft/vscode-eslint/issues/656
This is intended to clarify that documentation so that future pain and suffering may be avoided
=> Clarify `changeProcessCWD` documentation

server/src/eslintServer.ts
For some issues eslint triggers error with no `endLine` and/or
`endColumn` defined. In that case the code should use `line` and
`column` for the values, respectively. While the code has attempted to
do that, it only checked for `null` value for those while eslint
actually doesn't even have them set so they are undefined.
Fix by checking that value is either null or undefined.
This problem causes random exceptions on some LSP clients (for me it
triggered in Sublime LSP). Not sure if it affected Vetur.
Resolves #752
=> Fix None position values in publishDiagnostics message

README.md
VS Code wasn't linting my `.tsx` files even though running the CLI `eslint` with the correct glob patterns did the job. It took me thirty minutes to realize that this is because `tsx` files fell under the purview of `typescriptreact`, and so that also needed to be in `eslint.validate` for things to work as expected.
=> Add `typescriptreact` to the README's TypeScript section

server/src/eslintServer.ts
This PR makes the suggestions API added in ESLint v6.7 available via the quick fix.
---
close #806
=> Add to support new eslint suggestions API 

package.json
=> Treat all files with an `eslintignore` extension as ignore files

server/src/eslintServer.ts
Disable rule for entire file inserts the comment under the shebang.
Before:
```javascript
/* eslint-disable no-unused-vars */
#!/usr/bin/env node
```
After:
```javascript
#!/usr/bin/env node
/* eslint-disable no-unused-vars */
```
Closes #762
=> Disable rule for entire file inserts the comment under the shebang.

package.json
See docs: https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location
=> support remote development by indicating this is a workspace-only extension

client/src/extension.ts
Sync eslintAlwaysAllowExecutionKey
Fixes #1127
=> Sync eslintAlwaysAllowExecutionKey

package.json
As per: https://github.com/microsoft/vscode-eslint/blob/af8bc9924a35e2adf876dc8c4af0467f390945e9/server/src/eslintServer.ts#L157-L163
It looks like `eslint.codeAction.disableRuleComment` and `eslint.codeAction.showDocumentation` don't have any other properties. We should set `additionalProperties: false` in this case.
=> Add `additionalProperties: false` to some settings

client/src/extension.ts
Align wording with text string in l:537
=> Align text wording with actual button text

README.md, client/src/extension.ts, package.json, playgrounds/6.0/.vscode/settings.json, playgrounds/6.0/test.js, server/src/eslintServer.ts, server/src/linkedMap.ts
Continues @jamesorlakin's great work from https://github.com/microsoft/vscode-eslint/pull/993, with the changes requested by @dbaeumer to take settings as an array and allow ignoring rules.
Fixes #468 based on the discussions in #561.
Fixes #1199.
In the demo, note the underline under `bar` and `console.log` changing to red (error):
https://user-images.githubusercontent.com/3335181/110977314-0924af00-8330-11eb-8142-79b6fc8e85c9.mov
Co-authored-by: James Lakin <contact@jameslakin.co.uk>
=> Implement eslint.rules.customizations - with overrides

client/src/extension.ts, package.json, playgrounds/6.0/.eslintrc.json, playgrounds/6.0/.vscode/settings.json, server/src/eslintServer.ts
This PR adds the value `off` to `eslint.rules.customizations`, allowing the user to disable the report of selected rules in the editor.
=> Add severity "off" to eslint.rules.customizations

README.md, package.json, server/src/eslintServer.ts
This PR supports ESLint v8.
Specifically, change it to use the `ESLint` class instead of the removed `CLIEngine`.
However, for backward compatibility, if `CLIEngine` is present, use `CLIEngine`. See [`ESLintClassEmulator` class](https://github.com/microsoft/vscode-eslint/pull/1317/files#diff-f2161f943f61b946208678b9aa18cc18638bc3fe7cb19d2230ce939dc60165afR1496).
I checked that this change works by making sure that the marker appears in each of the environments where `eslint@8.0.0-beta.0`, `eslint@7.32.0`, and `eslint@6.8.0` are installed.
=> Supports ESLint v8.

server/src/eslintServer.ts
Based on @dbaeumer 's changes in: https://github.com/microsoft/vscode-eslint/commit/35f5fb950065e2223cf5911ae7ff2e2a4e1d1ade 
I added `graphql` language to the list of supported languages. This will make a better integration with https://github.com/dotansimha/graphql-eslint
=> Added graphql language to ESLint-server comments

server/src/eslintServer.ts
Hi @dbaeumer,
I was studying a way to contribute with #1357 and stepped on two small issues: a bug leading to stale entries on `saveRuleConfigCache` object, and behavior different from the documentation when using `eslint.codeActionsOnSave.rules` with ESLint version 8.
The stale cache is being caused by the use of the file URI to delete cache entries when a file is closed, those entries are indexed by the file path, not the URI. This fix only gets the file path from the URI and uses it to delete the cache entries, it was the simplest solution, but maybe using the URI to index cache entries could be a better one?
The behavior problem is because the function `getSaveRuleConfig` always returns undefined if `eslint.useESLintClass == false`, this makes sense to ESLint version 7, but not for …
=> Minor fixes for eslint.codeActionsOnSave.rules mechanism

client/src/extension.ts, server/src/eslintServer.ts
This PR resolves #1206 by allowing users to ignore server errors _by error message_ until the server is restarted.
The error dialog is not displayed, but the error is still shown on the output channel.
=> Allow user to ignore server errors.

server/src/eslintServer.ts
In order for the server to remain flexible and useful to many clients, the server must check the client's capabilities in the following scenarios:
1. Before including the `codeActionProvider` in its capabilities, it must ensure that the client signals code action literal support via the `textDocument.codeAction.codeActionLiteralSupport` property.
2. Before registering for the "workspace/didChangeConfiguration", the server must check that such dynamic registration is allowed.
This PR adds both checks.
=> Use client capabilities

package.json
This PR fixes a typo in the tooltip description of the `eslint.codeActionsOnSave.mode` popup. It also corrects the grammar, changing “Only fixes” to the more correct “Fixes only”.
=> Fix a typo in `package.json`

package-json-schema.json
It seems that #1027 did not address all occurrences of `http`.
See:
- https://github.com/microsoft/vscode/issues/40736
- https://github.com/microsoft/vscode/pull/40737
=> Change http to https for schemastore.org

$shared/settings.ts, client/src/client.ts, contributing.md, package.json, server/src/eslintServer.ts
Adds support for the feature requested in #1490.
=> Setting for comment style when disabling a line

$shared/settings.ts, client/src/client.ts, package.json, server/src/eslint.ts
I rebased #463 in hopes that you'll reconsider merging this useful feature.
Your main concern seems to be consistency, but that's not a concern shared by ESLint maintainers:
> In [#8004](https://github.com/eslint/eslint/issues/8004), it was decided that ESLint should report large ranges if a node with a large range is reported by a rule, and **allow integrations to display a smaller report if desired**. The reasoning is that different integrations will have different needs with regard to report ranges (for example, an integration that posts comments on GitHub might want to know the entire reported range, whereas **an editor integration might only want to highlight a subset of a reported range**).
> [*Source*](https://github.com/eslint/eslint/issues/10424#issuecomment-394526121) …
=> Introduce option to prevent underlining multiple lines

client/src/client.ts, package.json
=> Add “ignore untitled” setting

$shared/customMessages.ts, README.md, client/src/client.ts, server/src/eslintServer.ts
=> Fixes #1542: Add a status indication on how long the ESLint validation took. That is especially helpful for fix on save

playgrounds/flatConfig/.vscode/settings.json, server/src/eslint.ts
That seems to be some outdated info here?
=> Fix setting in playground

README.md
This setting was renamed in 2.2.2: https://github.com/microsoft/vscode-eslint/blob/main/CHANGELOG.md#222
=> Rename `eslint.runtime.execArgv` to `eslint.execArgv` in README

server/src/eslint.ts, server/src/eslintServer.ts
=> Handle unused directive problems

server/src/paths.ts
Re-opening https://github.com/microsoft/vscode-eslint/pull/1560 after the discussion in https://github.com/microsoft/language-server-protocol/pull/1679.
---
When using the ESLint language server in Neovim, creating a new unwritten buffer will cause the language server to crash due to `fs.realpathSync.native` throwing an exception since the file does not exist.  This change simply ignores errors from `fs.realpathSync.native` falling back to the original URI for the file.
=> Gracefully fail if file is not written to disk

playgrounds/flatConfig/eslint.config.js
The key `sourceType` is direct under `languageOptions` according to [Configuration Files (New) in ESLint docs](https://eslint.org/docs/latest/use/configure/configuration-files-new#configuration-objects).
=> fix(playgrounds-flatconfig): fix incorrect the key sourceType position

package.json, server/src/eslint.ts
This adds support for probing MDX based on [`eslint-plugin-mdx`](https://github.com/mdx-js/eslint-mdx/tree/master/packages/eslint-plugin-mdx). Probing MDX is is enabled by default for the `mdx` language id.
=> Support probing MDX

package.json, server/src/eslint.ts
This adds support for probing Astro based on [`eslint-plugin-astro`](https://github.com/ota-meshi/eslint-plugin-astro). Probing Astro is is enabled by default for the `astro` language id.
=> Support probing Astro

package.json
=> fix: add json, jsonc to `eslint.probe`'s default options

$shared/settings.ts, README.md, client/src/client.ts, server/src/eslint.ts
With the config like this:
```js
"eslint.rules.customizations": [
{ "rule": "*", "fixable": true, "severity": "info" }
]
```
It'll downgrade all autofixable problems to the info severity.
Before:
After:
This pull request is based on abandoned #1705, and incorporates all the feedback.
Fixes #1634
Rel #267, #680, #655, #1705
=> feat: Allow eslint.rules.customizations to target all fixable rules

$shared/settings.ts, server/src/eslint.ts
=> Fix #1886: Should plugins still have eslint.experimental.useFlatConfig in their settings?

contributing.md
To ease contributions, this PR makes the following changes to `contributing.md`:
- Add the necessary `git` command to enable symlinks locally. 
- Replace `npm install` by `npm ci` to make `npm` use the `package-lock.json`.
- Removes the outdated reference to the "Attach to server" launch configuration.
=> Update contributing instructions

README.md
According to the https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-mib, the argument is kebab-case, not snake_case
=> Fix casing on `eslint.execArgv` example

README.md
=> Fixes #2009: Settings documentation

package.json, server/src/eslint.ts
This will allow the plugin to automatically support Ember's glimmer-js / glimmer-ts files without needing to manually configure `eslint.validate`
=> Add probe support for Ember's glimmer-ts/glimmer-js format

client/src/client.ts
Use optional chaining for workspace folder lookup
- Uses optional chaining syntax that's already used elsewhere in the codebase
- No funtional changes to the behavior, but, improve code readability by eliminating the need to consider ternary operator precedence
=> Fix workspaceFolder check to use optional chaining
